workspace(name = 'use_local_markdownlint')

local_repository(
    name = 'dwtj_rules_markdown',
    path = '../..',
)

load('@dwtj_rules_markdown//markdown:defs.bzl', 'local_markdownlint_external_repository')

local_markdownlint_external_repository(
    name = 'local_markdownlint',
    config = "@//:.markdownlint.json",
)

load('@local_markdownlint//:defs.bzl', 'register_local_markdownlint_toolchain')

register_local_markdownlint_toolchain()
