load(
    "//markdown/toolchains/lint/known_toolchain_instances/remote/nodejs_markdownlint_cli/x86_64:defs.bzl",
    "make_default_markdown_lint_toolchain_for_platform_os"
)

#print('TODO(dwtj): Re-enable me.')
make_default_markdown_lint_toolchain_for_platform_os(platform_os = "@platforms//os:windows")
